kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp_path: "secret/data/helloworld"
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>